document.write('<div class="feedburnerFeedBlock" id="blogspot/UTweakgqmvt0lsf2l60bdh4e1o6rav60">');
document.write('<ul>');
document.write('<li><span class="headline"><a href="http://www.ubucentrum.net/2009/08/dystrybucje-linuksa-dla-pendrive-z.html" target="_blank" >Dystrybucje Linuksa dla Pendrive z instrukcjami do wgrania z poziomu Windowsa</a></span>');
document.write('</li>');
document.write('<li><span class="headline"><a href="http://www.ubucentrum.net/2009/08/humor-jak-bill-gates-powstrzyma.html" target="_blank" >Humor: Jak Bill Gates powstrzyma huragany? [wideo]</a></span>');
document.write('</li>');
document.write('<li><span class="headline"><a href="http://www.ubucentrum.net/2009/08/humor-wiewiorka-zatrzesa-swiatem.html" target="_blank" >Humor: Wiewi\u00F3rka zatrz\u0119s\u0142a \u015Bwiatem Linuksa</a></span>');
document.write('</li>');
document.write('<li><span class="headline"><a href="http://www.ubucentrum.net/2009/08/wyswietlanie-okadek-z-mpd-w-conky.html" target="_blank" >Wy\u015Bwietlanie ok\u0142adek z MPD w Conky</a></span>');
document.write('</li>');
document.write('</ul>');
document.write(' <div id="creditfooter"><a href="http://www.feedburner.com" target="_blank"><img src="http://www.feedburner.com/fb/images/buzzboost-pwrd.gif" alt="Headlines by FeedBurner" style="border:0"/></a></div>');
document.write('</div>');
